import { FilterCategoryDef, FilterGroup } from "@/lib/types";

/**
 * The Creative Filters taxonomy for the Bracelet Idea Generator. Structured
 * as FilterGroup[]/FilterCategoryDef[] so it can reuse the existing
 * FilterPanel/Chip/CategorySection UI components, even though bracelet
 * concepts aren't produced via GeneratorBlueprint.compose().
 */

export const braceletCategories: FilterCategoryDef[] = [
  {
    id: "creative-direction",
    label: "Theme & Style",
    helper: "The creative world this bracelet lives in.",
    defaultOpen: true,
  },
  {
    id: "feeling",
    label: "Aesthetic & Emotion",
    helper: "The vibe and feeling the piece should evoke.",
    defaultOpen: true,
  },
  {
    id: "occasion-color",
    label: "Occasion & Color",
    helper: "Who it's for and the palette it should live in.",
  },
  {
    id: "materials",
    label: "Materials",
    helper: "What it should actually be made from — gemstones, metal, cord, findings, and more.",
  },
];

export const braceletGroups: FilterGroup[] = [
  // --- Theme & Style --------------------------------------------------
  {
    id: "theme",
    label: "Theme",
    categoryId: "creative-direction",
    searchable: true,
    optional: true,
    allowCustom: true,
    customPlaceholder: "e.g. Northern lights, coral reef...",
    options: [
      { id: "flowers", label: "Flowers" },
      { id: "ocean", label: "Ocean" },
      { id: "forest", label: "Forest" },
      { id: "mountains", label: "Mountains" },
      { id: "desert", label: "Desert" },
      { id: "moon", label: "Moon" },
      { id: "stars", label: "Stars" },
      { id: "zodiac", label: "Zodiac" },
      { id: "butterflies", label: "Butterflies" },
      { id: "bees", label: "Bees" },
      { id: "autumn", label: "Autumn" },
      { id: "spring", label: "Spring" },
      { id: "winter", label: "Winter" },
      { id: "summer", label: "Summer" },
      { id: "japanese", label: "Japanese" },
      { id: "scandinavian-theme", label: "Scandinavian" },
      { id: "vintage-theme", label: "Vintage" },
      { id: "botanical", label: "Botanical" },
      { id: "celestial", label: "Celestial" },
      { id: "woodland", label: "Woodland" },
      { id: "tropical", label: "Tropical" },
    ],
  },
  {
    id: "style",
    label: "Bracelet Style",
    categoryId: "creative-direction",
    searchable: true,
    optional: true,
    options: [
      // Beaded
      { id: "gemstone-beaded", label: "Gemstone Beaded" },
      { id: "seed-bead", label: "Seed Bead" },
      { id: "czech-glass", label: "Czech Glass" },
      { id: "pearl-beaded", label: "Pearl" },
      { id: "crystal-beaded", label: "Crystal" },
      { id: "mixed-beads", label: "Mixed Beads" },
      // Thread
      { id: "friendship", label: "Friendship" },
      { id: "macrame", label: "Macramé" },
      { id: "braided", label: "Braided" },
      { id: "silk-thread", label: "Silk" },
      { id: "waxed-cord", label: "Waxed Cord" },
      { id: "adjustable-knot", label: "Adjustable Knot" },
      // Metal
      { id: "chain", label: "Chain" },
      { id: "paperclip", label: "Paperclip" },
      { id: "cuban", label: "Cuban" },
      { id: "figaro", label: "Figaro" },
      { id: "bangle", label: "Bangle" },
      { id: "cuff", label: "Cuff" },
      { id: "wire-wrapped", label: "Wire Wrapped" },
      // Natural
      { id: "wood-style", label: "Wood" },
      { id: "lava-stone", label: "Lava Stone" },
      { id: "shell", label: "Shell" },
      { id: "mother-of-pearl", label: "Mother of Pearl" },
      { id: "leather-style", label: "Leather" },
      { id: "hemp-style", label: "Hemp" },
    ],
  },

  // --- Aesthetic & Emotion --------------------------------------------
  {
    id: "aesthetic",
    label: "Aesthetic",
    categoryId: "feeling",
    multiple: true,
    searchable: true,
    optional: true,
    options: [
      { id: "quiet-luxury", label: "Quiet Luxury" },
      { id: "old-money", label: "Old Money" },
      { id: "minimalist-aesthetic", label: "Minimalist" },
      { id: "modern-organic", label: "Modern Organic" },
      { id: "cottagecore", label: "Cottagecore" },
      { id: "fairycore", label: "Fairycore" },
      { id: "boho", label: "Boho" },
      { id: "romantic-aesthetic", label: "Romantic" },
      { id: "editorial-aesthetic", label: "Editorial" },
      { id: "vintage-aesthetic", label: "Vintage" },
      { id: "coastal", label: "Coastal" },
      { id: "rustic", label: "Rustic" },
      { id: "scandinavian-aesthetic", label: "Scandinavian" },
      { id: "parisian", label: "Parisian" },
      { id: "art-deco-aesthetic", label: "Art Deco" },
      { id: "gothic-aesthetic", label: "Gothic" },
      { id: "steampunk-aesthetic", label: "Steampunk" },
      { id: "cyberpunk-aesthetic", label: "Cyberpunk" },
      { id: "fantasy-aesthetic", label: "Fantasy" },
      { id: "ethereal", label: "Ethereal" },
    ],
  },
  {
    id: "emotion",
    label: "Emotion",
    categoryId: "feeling",
    multiple: true,
    optional: true,
    options: [
      { id: "peaceful", label: "Peaceful" },
      { id: "confident", label: "Confident" },
      { id: "romantic-emotion", label: "Romantic" },
      { id: "feminine", label: "Feminine" },
      { id: "powerful", label: "Powerful" },
      { id: "cozy", label: "Cozy" },
      { id: "joyful", label: "Joyful" },
      { id: "delicate", label: "Delicate" },
      { id: "adventurous", label: "Adventurous" },
      { id: "elegant", label: "Elegant" },
      { id: "nostalgic", label: "Nostalgic" },
      { id: "hopeful", label: "Hopeful" },
    ],
  },

  // --- Occasion & Color --------------------------------------------------
  {
    id: "occasion",
    label: "Occasion",
    categoryId: "occasion-color",
    optional: true,
    options: [
      { id: "everyday-wear", label: "Everyday Wear" },
      { id: "birthday", label: "Birthday" },
      { id: "wedding", label: "Wedding" },
      { id: "bridesmaid", label: "Bridesmaid" },
      { id: "anniversary", label: "Anniversary" },
      { id: "mothers-day", label: "Mother's Day" },
      { id: "christmas", label: "Christmas" },
      { id: "valentines-day", label: "Valentine's Day" },
      { id: "graduation", label: "Graduation" },
      { id: "friendship-occasion", label: "Friendship" },
      { id: "self-love", label: "Self Love" },
    ],
  },
  {
    id: "colorPalette",
    label: "Color Palette",
    categoryId: "occasion-color",
    searchable: true,
    optional: true,
    options: [
      { id: "cream-gold", label: "Cream & Gold" },
      { id: "earth-tones", label: "Earth Tones" },
      { id: "sage-green", label: "Sage Green" },
      { id: "ocean-blues", label: "Ocean Blues" },
      { id: "sunset", label: "Sunset" },
      { id: "autumn-palette", label: "Autumn" },
      { id: "monochrome", label: "Monochrome" },
      { id: "jewel-tones", label: "Jewel Tones" },
      { id: "pastel", label: "Pastel" },
      { id: "black-gold", label: "Black & Gold" },
      { id: "rose-gold-palette", label: "Rose Gold" },
      { id: "neutral-luxury", label: "Neutral Luxury" },
    ],
  },

  // --- Materials -------------------------------------------------------
  // Split into focused sub-groups (rather than one giant flat list) so the
  // Materials category stays scannable/searchable even though it covers
  // ~190 options across everything from gemstones to jewelry hardware.
  {
    id: "materialGemstones",
    label: "Natural Gemstones",
    categoryId: "materials",
    helper: "Crystals and stone beads for the main body of the piece.",
    multiple: true,
    searchable: true,
    optional: true,
    allowCustom: true,
    customPlaceholder: "e.g. Rainbow Moonstone, Ethiopian Opal...",
    options: [
      { id: "amethyst", label: "Amethyst" },
      { id: "rose-quartz", label: "Rose Quartz" },
      { id: "clear-quartz", label: "Clear Quartz" },
      { id: "smoky-quartz", label: "Smoky Quartz" },
      { id: "citrine", label: "Citrine" },
      { id: "peridot", label: "Peridot" },
      { id: "moss-agate", label: "Moss Agate" },
      { id: "tree-agate", label: "Tree Agate" },
      { id: "green-aventurine", label: "Green Aventurine" },
      { id: "blue-aventurine", label: "Blue Aventurine" },
      { id: "carnelian", label: "Carnelian" },
      { id: "amazonite", label: "Amazonite" },
      { id: "aquamarine", label: "Aquamarine" },
      { id: "apatite", label: "Apatite" },
      { id: "labradorite", label: "Labradorite" },
      { id: "moonstone", label: "Moonstone" },
      { id: "sunstone", label: "Sunstone" },
      { id: "lapis-lazuli", label: "Lapis Lazuli" },
      { id: "sodalite", label: "Sodalite" },
      { id: "turquoise", label: "Turquoise" },
      { id: "howlite", label: "Howlite" },
      { id: "malachite", label: "Malachite" },
      { id: "fluorite", label: "Fluorite" },
      { id: "jade", label: "Jade" },
      { id: "serpentine", label: "Serpentine" },
      { id: "unakite", label: "Unakite" },
      { id: "bloodstone", label: "Bloodstone" },
      { id: "black-tourmaline", label: "Black Tourmaline" },
      { id: "tigers-eye", label: "Tiger's Eye" },
      { id: "hawks-eye", label: "Hawk's Eye" },
      { id: "red-jasper", label: "Red Jasper" },
      { id: "picture-jasper", label: "Picture Jasper" },
      { id: "ocean-jasper", label: "Ocean Jasper" },
      { id: "kambaba-jasper", label: "Kambaba Jasper" },
      { id: "dalmatian-jasper", label: "Dalmatian Jasper" },
      { id: "rhodonite", label: "Rhodonite" },
      { id: "rhodochrosite", label: "Rhodochrosite" },
      { id: "lepidolite", label: "Lepidolite" },
      { id: "chrysoprase", label: "Chrysoprase" },
      { id: "chrysocolla", label: "Chrysocolla" },
      { id: "prehnite", label: "Prehnite" },
      { id: "garnet", label: "Garnet" },
      { id: "iolite", label: "Iolite" },
      { id: "kyanite", label: "Kyanite" },
      { id: "onyx", label: "Onyx" },
      { id: "obsidian", label: "Obsidian" },
      { id: "hematite", label: "Hematite" },
      { id: "pyrite", label: "Pyrite" },
    ],
  },
  {
    id: "materialGlassCrystalPearl",
    label: "Glass, Crystal & Pearl Beads",
    categoryId: "materials",
    helper: "Seed beads, faceted crystal, and pearls.",
    multiple: true,
    searchable: true,
    optional: true,
    allowCustom: true,
    customPlaceholder: "e.g. Tahitian Pearls, AB-coated crystal...",
    options: [
      { id: "czech-glass-beads", label: "Czech Glass Beads" },
      { id: "japanese-seed-beads", label: "Japanese Seed Beads" },
      { id: "miyuki-delica", label: "Miyuki Delica" },
      { id: "toho-seed-beads", label: "Toho Seed Beads" },
      { id: "fire-polished-beads", label: "Fire Polished Beads" },
      { id: "lampwork-beads", label: "Lampwork Beads" },
      { id: "murano-glass", label: "Murano Glass" },
      { id: "crackle-glass", label: "Crackle Glass" },
      { id: "faceted-glass", label: "Faceted Glass" },
      { id: "bugle-beads", label: "Bugle Beads" },
      { id: "swarovski-crystal", label: "Swarovski Crystal" },
      { id: "preciosa-crystal", label: "Preciosa Crystal" },
      { id: "bicone-crystal", label: "Bicone Crystal" },
      { id: "rivoli-crystal", label: "Rivoli Crystal" },
      { id: "crystal-pearls", label: "Crystal Pearls" },
      { id: "freshwater-pearls", label: "Freshwater Pearls" },
      { id: "akoya-pearls", label: "Akoya Pearls" },
      { id: "baroque-pearls", label: "Baroque Pearls" },
      { id: "shell-pearls", label: "Shell Pearls" },
      { id: "glass-pearls", label: "Glass Pearls" },
      { id: "keshi-pearls", label: "Keshi Pearls" },
    ],
  },
  {
    id: "materialMetal",
    label: "Metal",
    categoryId: "materials",
    helper: "Precious and base metals for beads, findings, and accents.",
    multiple: true,
    searchable: true,
    optional: true,
    allowCustom: true,
    customPlaceholder: "e.g. Oxidized silver, black rhodium...",
    options: [
      { id: "sterling-silver", label: "Sterling Silver" },
      { id: "gold-filled", label: "Gold Filled" },
      { id: "gold-plated", label: "Gold Plated" },
      { id: "rose-gold", label: "Rose Gold" },
      { id: "vermeil", label: "Vermeil" },
      { id: "brass", label: "Brass" },
      { id: "copper", label: "Copper" },
      { id: "stainless-steel", label: "Stainless Steel" },
      { id: "aluminum", label: "Aluminum" },
      { id: "hammered-metal", label: "Hammered Metal" },
      { id: "bali-silver", label: "Bali Silver" },
      { id: "titanium", label: "Titanium" },
    ],
  },
  {
    id: "materialOrganic",
    label: "Organic & Natural",
    categoryId: "materials",
    helper: "Wood, shell, bone, and other natural materials.",
    multiple: true,
    searchable: true,
    optional: true,
    allowCustom: true,
    customPlaceholder: "e.g. Palm wood, deer antler...",
    options: [
      { id: "wood", label: "Wood" },
      { id: "sandalwood", label: "Sandalwood" },
      { id: "olive-wood", label: "Olive Wood" },
      { id: "coconut-shell", label: "Coconut Shell" },
      { id: "tagua-nut", label: "Tagua Nut" },
      { id: "bone", label: "Bone" },
      { id: "horn", label: "Horn" },
      { id: "amber", label: "Amber" },
      { id: "coral-ethical", label: "Coral (Ethically Sourced)" },
      { id: "mother-of-pearl", label: "Mother of Pearl" },
      { id: "abalone-shell", label: "Abalone Shell" },
      { id: "lava-stone", label: "Lava Stone" },
      { id: "sea-glass", label: "Sea Glass" },
      { id: "driftwood", label: "Driftwood" },
      { id: "cork", label: "Cork" },
    ],
  },
  {
    id: "materialPolymerResin",
    label: "Polymer, Acrylic & Resin",
    categoryId: "materials",
    helper: "Clay, acrylic, and cast-resin components.",
    multiple: true,
    searchable: true,
    optional: true,
    allowCustom: true,
    customPlaceholder: "e.g. Glow-in-the-dark resin...",
    options: [
      { id: "polymer-clay", label: "Polymer Clay" },
      { id: "acrylic", label: "Acrylic" },
      { id: "resin-beads", label: "Resin Beads" },
      { id: "uv-resin", label: "UV Resin" },
      { id: "epoxy-resin", label: "Epoxy Resin" },
      { id: "silicone", label: "Silicone" },
      { id: "rubber", label: "Rubber" },
    ],
  },
  {
    id: "materialCordThread",
    label: "Cord, Thread & Stringing",
    categoryId: "materials",
    helper: "What the beads are strung or knotted onto.",
    multiple: true,
    searchable: true,
    optional: true,
    allowCustom: true,
    customPlaceholder: "e.g. Waxed hemp, kumihimo cord...",
    options: [
      { id: "stretch-elastic-cord", label: "Stretch / Elastic Cord" },
      { id: "nylon-thread", label: "Nylon Thread" },
      { id: "silk-thread-cord", label: "Silk Thread" },
      { id: "waxed-cotton-cord", label: "Waxed Cotton Cord" },
      { id: "waxed-linen", label: "Waxed Linen" },
      { id: "embroidery-floss", label: "Embroidery Floss" },
      { id: "s-lon-cord", label: "S-Lon Cord" },
      { id: "c-lon-cord", label: "C-Lon Cord" },
      { id: "round-leather-cord", label: "Round Leather Cord" },
      { id: "flat-leather-cord", label: "Flat Leather Cord" },
      { id: "braided-leather", label: "Braided Leather" },
      { id: "vegan-leather", label: "Vegan Leather" },
      { id: "suede-cord", label: "Suede Cord" },
      { id: "cotton-cord", label: "Cotton Cord" },
      { id: "hemp-cord", label: "Hemp Cord" },
      { id: "jute", label: "Jute" },
      { id: "satin-cord", label: "Satin Cord" },
      { id: "paracord", label: "Paracord" },
      { id: "micro-cord", label: "Micro Cord" },
      { id: "memory-wire", label: "Memory Wire" },
      { id: "beading-wire", label: "Beading Wire (Tiger Tail)" },
      { id: "copper-wire", label: "Copper Wire" },
      { id: "brass-wire", label: "Brass Wire" },
      { id: "sterling-silver-wire", label: "Sterling Silver Wire" },
      { id: "artistic-wire", label: "Artistic Wire" },
    ],
  },
  {
    id: "materialChainsFindings",
    label: "Chains, Clasps & Findings",
    categoryId: "materials",
    helper: "Chain styles, clasps, and small metal hardware.",
    multiple: true,
    searchable: true,
    optional: true,
    allowCustom: true,
    customPlaceholder: "e.g. Curb chain, screw clasp...",
    options: [
      { id: "cable-chain", label: "Cable Chain" },
      { id: "figaro-chain", label: "Figaro Chain" },
      { id: "box-chain", label: "Box Chain" },
      { id: "rolo-chain", label: "Rolo Chain" },
      { id: "snake-chain", label: "Snake Chain" },
      { id: "ball-chain", label: "Ball Chain" },
      { id: "satellite-chain", label: "Satellite Chain" },
      { id: "paperclip-chain", label: "Paperclip Chain" },
      { id: "cuban-chain", label: "Cuban Chain" },
      { id: "wheat-chain", label: "Wheat Chain" },
      { id: "lobster-clasp", label: "Lobster Clasp" },
      { id: "toggle-clasp", label: "Toggle Clasp" },
      { id: "magnetic-clasp", label: "Magnetic Clasp" },
      { id: "box-clasp", label: "Box Clasp" },
      { id: "hook-clasp", label: "Hook Clasp" },
      { id: "barrel-clasp", label: "Barrel Clasp" },
      { id: "s-hook-clasp", label: "S-Hook Clasp" },
      { id: "spring-ring-clasp", label: "Spring Ring Clasp" },
      { id: "jump-rings", label: "Jump Rings" },
      { id: "split-rings", label: "Split Rings" },
      { id: "crimp-beads", label: "Crimp Beads" },
      { id: "crimp-covers", label: "Crimp Covers" },
      { id: "bead-caps", label: "Bead Caps" },
      { id: "spacer-beads", label: "Spacer Beads" },
      { id: "eye-pins", label: "Eye Pins" },
      { id: "head-pins", label: "Head Pins" },
      { id: "cord-ends", label: "Cord Ends" },
      { id: "end-caps", label: "End Caps" },
      { id: "connectors", label: "Connectors" },
      { id: "wire-guardians", label: "Wire Guardians" },
    ],
  },
  {
    id: "materialDecorative",
    label: "Decorative & Textile",
    categoryId: "materials",
    helper: "Ribbon, tassels, fabric, and natural embellishments.",
    multiple: true,
    searchable: true,
    optional: true,
    allowCustom: true,
    customPlaceholder: "e.g. Raffia, embroidered ribbon...",
    options: [
      { id: "silk-ribbon", label: "Silk Ribbon" },
      { id: "velvet-ribbon", label: "Velvet Ribbon" },
      { id: "organza-ribbon", label: "Organza Ribbon" },
      { id: "satin-ribbon", label: "Satin Ribbon" },
      { id: "lace", label: "Lace" },
      { id: "silk-tassels", label: "Silk Tassels" },
      { id: "cotton-tassels", label: "Cotton Tassels" },
      { id: "pom-poms", label: "Pom-Poms" },
      { id: "dried-flowers", label: "Dried Flowers" },
      { id: "pressed-flowers", label: "Pressed Flowers" },
      { id: "fabric-strips", label: "Fabric Strips" },
      { id: "denim", label: "Denim" },
      { id: "linen", label: "Linen" },
      { id: "felt", label: "Felt" },
      { id: "velvet-fabric", label: "Velvet" },
      { id: "shell-chips", label: "Shell Chips" },
      { id: "seeds", label: "Seeds" },
      { id: "acorns", label: "Acorns" },
      { id: "pine-beads", label: "Pine Beads" },
    ],
  },
  {
    id: "materialSpecialty",
    label: "Specialty & Personalization",
    categoryId: "materials",
    helper: "Ceramic, recycled materials, and personalized touches.",
    multiple: true,
    searchable: true,
    optional: true,
    allowCustom: true,
    customPlaceholder: "e.g. Engraved bar, birth flower charm...",
    options: [
      { id: "ceramic", label: "Ceramic" },
      { id: "porcelain", label: "Porcelain" },
      { id: "concrete-beads", label: "Concrete Beads" },
      { id: "recycled-glass", label: "Recycled Glass" },
      { id: "vintage-trade-beads", label: "Vintage / Trade Beads" },
      { id: "recycled-metal", label: "Recycled Metal" },
      { id: "upcycled-leather", label: "Upcycled Leather" },
      { id: "alphabet-beads", label: "Alphabet Beads" },
      { id: "number-beads", label: "Number Beads" },
      { id: "morse-code-beads", label: "Morse Code Beads" },
      { id: "birthstone-beads", label: "Birthstone Beads" },
      { id: "zodiac-charms", label: "Zodiac Charms" },
      { id: "evil-eye-charms", label: "Evil Eye Charms" },
      { id: "hamsa-charms", label: "Hamsa Charms" },
      { id: "initial-charms", label: "Initial Charms" },
      { id: "diffuser-beads", label: "Diffuser Beads" },
    ],
  },
];

/** All Materials-category group ids, in display order — used to aggregate
 *  every material selection into one flat list (see concept-generator.ts). */
export const MATERIAL_GROUP_IDS = [
  "materialGemstones",
  "materialGlassCrystalPearl",
  "materialMetal",
  "materialOrganic",
  "materialPolymerResin",
  "materialCordThread",
  "materialChainsFindings",
  "materialDecorative",
  "materialSpecialty",
] as const;

export function findBraceletGroup(id: string): FilterGroup {
  const group = braceletGroups.find((g) => g.id === id);
  if (!group) throw new Error(`Unknown bracelet filter group: ${id}`);
  return group;
}
